### ISSUE TITLE
odd listing with Megan's login

### ISSUE THREAD

**Issue by swpcap** [starverte/lifepointe#13]
When Megan looks at a sermon series, it shows sermon 13-21, then 1-12.  I have checked different browsers and different computers.  If I log in, it shows 1-21 just fine, even on her computer in the Firefox browser she uses.  She sees it that way in IE or Firefox.  It works fine for me in IE and Chrome and in Firefox on her computer.  Any ideas?

thanks,
Steve

**Comment by mbeall** [comment]
This is a user preference, and they can be moved around. However, it should save the user's configuration and should be the same on all browsers. I will look into why it's just on IE.
