### ISSUE TITLE
contact form check box not presenting correctly

### ISSUE THREAD

**Issue by swpcap** [starverte/lifepointe#76]
on the sharethelife.org/survey form, there is a checkbox field.  The box is showing up in the middle of the text on top of the text, instead of at the beginning or end.

**Comment by swpcap** [comment]
In Chrome it is in the wrong place.  In IE, it is a similar position, but covers the text.

**Comment by mbeall** [comment]
The LifePointe theme has been discontinued, and the current theme is Trinity. This issue will be moved to that repository (https://github.com/starverte/trinity).

**Comment by mbeall** [comment]
This is actually an issue with Flint, so it has been moved there: https://github.com/starverte/flint/issues/183
