### ISSUE TITLE
Sermons stopping on playback

### ISSUE THREAD

**Issue by swpcap** [starverte/lifepointe#77]
I continue to get feedback and see it myself that the sermons stop after partial playback.  The latest was this past Sunday by a guest who was trying to listen to the sermons on her iPhone.

Can this be fixed?  If not, I’d suggest we take that option off the website and only allow for downloads.  I don’t want to do that, but users will quickly get frustrated with the playback stopping and leave our site.

**Comment by mbeall** [comment]
This issue doesn't refer to the lifepointe theme, which has been discontinued, and so has been reposted at https://github.com/starverte/trinity/issues/11
